GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.S3lsZQ.SPg_6ZnHcSyUz4MC48J-Yh7M7uxtmpNYAGo1ml20css


###

DELETE http://localhost:4000/logout Content-Type: application/json

{
"token": "eyJhbGciOiJIUzI1NiJ9.S3lsZQ.SPg_6ZnHcSyUz4MC48J-Yh7M7uxtmpNYAGo1ml20css"
}

###

POST http://localhost:4000/token 
Content-Type: application/json

{

"token": "eyJhbGciOiJIUzI1NiJ9.S3lsZQ.SPg_6ZnHcSyUz4MC48J-Yh7M7uxtmpNYAGo1ml20css"

}


###
POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "Kyle"
}

